### ISSUE TITLE
Bug on updating the LBs matrix!

### ISSUE THREAD

**Issue by weixians** [zcaicaros/L2D#13]
I found there might be a bug on computing the lower bounds which is "LBs" in the code. Sometimes the updated lower bounds is wrong and this might be a critical issue! 
Please set "env_num=1" and debug to see if the LBs is correct.

**Comment by zcaicaros** [comment]
Hi, thank you for raising the issue. May I know what the bug is exactly? Also, can you show me some details so that I can reproduce your bug?, E.g., the random seed you use and other related details.

**Comment by weixians** [comment]
> Hi, thank you for raising the issue. May I know what the bug is exactly? Also, can you show me some details so that I can reproduce your bug?, E.g., the random seed you use and other related details.

Hi, all the papameter settings is the same expect for the n_j and n_m which I set them as 3, and num_env=1 for debug. And I think it is not because of random seeds.
Please set the num_env to 1 so that we can easily debug the status of LBs. Here I put a [link](https://imgse.com/i/xliOh9) of the image. We can see that after prcessing **the operation with id 1**, the lower bound for this node is **87**. However, the time should be **193**, since OP 1 is processed after OP5 and they both share machine 2.

**Comment by zcaicaros** [comment]
Hi, 

Thanks for the detailed example. Based on the adjacent matrix in the example you provide, I can see that there is a processing order: OP4 -> OP1 -> OP2, and this is the only path from Os to OP2, therefore, LB = finish time = OP4 + OP1 + OP2 = 43 + 27 + 17 = 87. 

Please note that in my code, the adjacent matrix is rows pointing to columns, i.e., I_ij = 1 means the node with id i is pointing to node j.

**Comment by weixians** [comment]
> Hi,
> 
> Thanks for the detailed example. Based on the adjacent matrix in the example you provide, I can see that there is a processing order: OP4 -> OP1 -> OP2, and this is the only path from Os to OP2, therefore, LB = finish time = OP4 + OP1 + OP2 = 43 + 27 + 17 = 87.
> 
> Please note that in my code, the adjacent matrix is rows pointing to columns, i.e., I_ij = 1 means the node with id i is pointing to node j.

Hi, but the OP2(id is 1) is finished after OP6 whose finished time is 176, so why it isn't 176+17=193?

**Comment by zcaicaros** [comment]
> > Hi,
> > Thanks for the detailed example. Based on the adjacent matrix in the example you provide, I can see that there is a processing order: OP4 -> OP1 -> OP2, and this is the only path from Os to OP2, therefore, LB = finish time = OP4 + OP1 + OP2 = 43 + 27 + 17 = 87.
> > Please note that in my code, the adjacent matrix is rows pointing to columns, i.e., I_ij = 1 means the node with id i is pointing to node j.
> 
> Hi, but the OP2(id is 1) is finished after OP6 whose finished time is 176, so why it isn't 176+17=193?

Please ignore the previous message, I mean the column pointing to row, i.e., `[0, 1, 0, 0, 1, 1, 0, 0, 0]` means OP6 is processed after OP2. The notation in my code is different from the conventional one. In my code, if the first row of the adjacent matrix is `[1, 0, 1, 0, 0, 0, 0, 0, 0]`, it means the first operation has two direct neighbours, one is itself (self-loop), and the other is the node with id 2 (the third node).

**Comment by weixians** [comment]
Yes, I know your adjacency is actually transposed since I see the .t() in g_pool_cal() function.

Oh, god! I hope I now understand what you mean. 
The opeartion order in a machine can actually be reordered according to the finish time. Take the example I uploaded in the image before. The finish time OP2 is 87, while the OP6 is 176, so even we first select OP6 for machine 2, we can change the order of [OP2, OP6] to [OP2, OP6]. Also, we may need to update the finish time of OP6 since the start time of OP6 now may be delayed because of processing OP2.
Is that correct?

**Comment by zcaicaros** [comment]
Yes, according to the paper, I implemented a left shift operator to adjust the processing order of dispatched operations, which may conflict with the original determined one. In your case, even though the agent assigns OP2 after OP6, if there is an empty slot before OP6 that can accommodate OP2, the env will insert OP2 into that position. Therefore, we get [OP2, OP6] instead.

**Comment by weixians** [comment]
Thanks a lot! I now fixed the confusion.

**Comment by free001a** [comment]
> Thanks a lot! I now fixed the confusion.

Hello, sorry to interrupt, this may be a violation of community etiquette, but I have no choice, please forgive me. I am very interested in this paper and the code, but there are some questions that nobody can ask and discuss, and I am struggling to solve them. I really hope to get others' advice. May I exchange my contact information with you, please?

Or do you think this is a violation of your privacy? I wrote my confusion in the latest issue, hoping to get some advice.

Thank you so much!
