### ISSUE TITLE
Remove the old arcs can make the graph embedding more accurate.

### ISSUE THREAD

**Issue by ShenGaopan** [zcaicaros/L2D#4]
Maybe we should remove the old arc when a new operation inserts between two operations. Removing the old disjunctive arcs can make the graph embedding more accurate. 
All we need is to add the following code to JSSP_Env.py -> def step(self, action).
```python
if flag and precd != action and succd != action:  # Remove the old arc when a new operation inserts between two operations
    self.adj[succd, precd] = 0
```

**Comment by zcaicaros** [comment]
Hi Gaopan, thanks for finding this mistake! It is been added to 7f9decac5f0f4cdf9536a10b40d5042a09957b05.

**Comment by free001a** [comment]
> Maybe we should remove the old arc when a new operation inserts between two operations. Removing the old disjunctive arcs can make the graph embedding more accurate. All we need is to add the following code to JSSP_Env.py -> def step(self, action).
> 
> ```python
> if flag and precd != action and succd != action:  # Remove the old arc when a new operation inserts between two operations
>     self.adj[succd, precd] = 0
> ```

Hello, sorry to interrupt, this may be a violation of community etiquette, but I have no choice, please forgive me. I am very interested in this paper and the code, but there are some questions that nobody can ask and discuss, and I am struggling to solve them. I really hope to get others' advice. May I exchange my contact information with you, please?

Or do you think this is a violation of your privacy? I wrote my confusion in the latest issue, hoping to get some advice.

Thank you so much!
