### ISSUE TITLE
update过程中的一个小bug

### ISSUE THREAD

**Issue by Chupeng24** [zcaicaros/L2D#5]
在代码文件PPO_jssp_multiInstances.py的update函数处： 
![image](https://user-images.githubusercontent.com/36120514/144392504-43430902-155a-4357-9367-b552f252ada8.png)

 以6x6 size的instance为例，在第一句标红框的位置line-138处，rewards_all_env[i] 的shape为（36，），vals的shape为（36，1），由于torch.tensor的广播机制，运算后advantages的shape为（36，36），随后的surr1、surr2的shape也为（36，36），在第二句标红框处，即line-142，p_loss的shape也为（36，36），最后导致loss的大小也为（36，36）。
这个过程跟PPO公式应该是不符合的，不过模型训练是可以收敛的。

我将上述两句改为以下符合PPO公式的情况，模型训练也能正常收敛，且效果比原来的略好。
![image](https://user-images.githubusercontent.com/36120514/144392537-b6165d63-213d-4e90-93bd-860e617e1ca7.png)
或者只修改line-142处，亦可达到同样目的。

模型训练及测试情况如下图所示，橙色是原版的情况，蓝色是修改后的情况：训练过程中Param中除instances size改为6x6外，其他没变过。
![image](https://user-images.githubusercontent.com/36120514/144392116-7c1ba10a-771c-4910-9bff-5466221f19ad.png)
经过初步调参，测试结果是有提升的。
如下图所示，绿色线为经过调参后的结果，best result 为 566.8，论文中的结果为574.09，比论文中的结果略好。
![image](https://user-images.githubusercontent.com/36120514/144392261-8dc60cba-211d-438d-90ba-864e53093383.png)

**Comment by zcaicaros** [comment]
Thank you for your contribution! This is now fixed and added in 20aa4f60d65d6f3e97a5a3609c99ef7c0ce0100d.

**Comment by free001a** [comment]
> 在代码文件PPO_jssp_multiInstances.py的update函数处： ![image](https://user-images.githubusercontent.com/36120514/144392504-43430902-155a-4357-9367-b552f252ada8.png)
> 
> 以6x6 size的instance为例，在第一句标红框的位置line-138处，rewards_all_env[i] 的shape为（36，），vals的shape为（36，1），由于torch.tensor的广播机制，运算后advantages的shape为（36，36），随后的surr1、surr2的shape也为（36，36），在第二句标红框处，即line-142，p_loss的shape也为（36，36），最后导致loss的大小也为（36，36）。 这个过程跟PPO公式应该是不符合的，不过模型训练是可以收敛的。
> 
> 我将上述两句改为以下符合PPO公式的情况，模型训练也能正常收敛，且效果比原来的略好。 ![image](https://user-images.githubusercontent.com/36120514/144392537-b6165d63-213d-4e90-93bd-860e617e1ca7.png) 或者只修改line-142处，亦可达到同样目的。
> 
> 模型训练及测试情况如下图所示，橙色是原版的情况，蓝色是修改后的情况：训练过程中Param中除instances size改为6x6外，其他没变过。 ![image](https://user-images.githubusercontent.com/36120514/144392116-7c1ba10a-771c-4910-9bff-5466221f19ad.png) 经过初步调参，测试结果是有提升的。 如下图所示，绿色线为经过调参后的结果，best result 为 566.8，论文中的结果为574.09，比论文中的结果略好。 ![image](https://user-images.githubusercontent.com/36120514/144392261-8dc60cba-211d-438d-90ba-864e53093383.png)

你好，冒昧打扰，此举可能违反了社区礼仪，但是我别无他法，请海涵。我对这篇论文和代码很感兴趣，但是有一些问题无人可询问讨论，并且苦思不得其解，非常希望获得别人的指点。请问我可以和你交换一下联系方式吗？我的微信是FLYFREE001a。

或者您认为此举侵犯了您的隐私，我在最新的issue中写明了我的困惑，希望可以得到指点。

感激不尽！
