### ISSUE TITLE
 Question about the PPO

### ISSUE THREAD

**Issue by Fish-III-C** [zcaicaros/L2D#7]
Thanks for your great work！

I found that both the new and the old policy use the same model at first which means that all the parameters in GNN/Actor/Critic network are same.

But why the same environment can get different logprob in policy_old and policy？

**Comment by zcaicaros** [comment]
Hi,

Thanks for your interest in this work.

Initially, the policy and the old policy will have the same set of parameters, and you are right about this. However, notice that, the PPO algorithm will update the policy network `K` times while the old policy will remain the same during updating. Therefore, it means for every `1 <= k <= K` iteration, PPO will compute a new `log_prob` with respect to the updated policy. In another word, the `log_prob` will be different at every `k` iteration while the `old log_prob` will remain the same, and this produces different `log_prob` for policy and old policy, thus is an `off-policy` learning.

Hope this hasty answer give you some clue. For details, I recommend you to refer to the [PPO paper](https://arxiv.org/abs/1707.06347 ).

Thanks.

**Comment by Fish-III-C** [comment]
Thank you for your answer！

I hope to ask some more about the first update:
When the new and old policy have the same parameters at first, how does the same input data get the different log_prob in the first iteration?

Thanks again.

**Comment by zcaicaros** [comment]
In this case, I think they are equivalent. So, if you set `K=1`, PPO will be an on-policy learning algorithm based on my understanding.

**Comment by zcaicaros** [comment]
Can reopen if there are still questions.

**Comment by edwardzcl** [comment]
> Can reopen if there are still questions.

I have the same question. Why the `old_policy` and `policy` get the different `log_prob` in the training stage when they are fed with the same input data and initialized with the same parameters. It should be noted the update time `k_epochs` equals to 1.

**Comment by zcaicaros** [comment]
Thanks for your question. You are right, in this paper, we adopted K=1, which means the PPO is updated in an on-policy manner. So the importance sampling trick no longer has any effect. Hope this answers your question.

**Comment by zcaicaros** [comment]
> > Can reopen if there are still questions.
> 
> I have the same question. Why the `old_policy` and `policy` get the different `log_prob` in the training stage when they are fed with the same input data and initialized with the same parameters. It should be noted the update time `k_epochs` equals to 1.

Thanks for your question. You are right, in this paper, we adopted K=1, which means the PPO is updated in an on-policy manner. So the importance sampling trick no longer has any effect. Hope this answers your question.
