### ISSUE TITLE
confuse about initialize adj matrix

### ISSUE THREAD

**Issue by beckhz** [zcaicaros/L2D#8]
![image](https://user-images.githubusercontent.com/13513093/172023785-f87e5b3d-b8ca-47d9-b0bf-32bb289f4715.png)
Hi，
The variable "conj_nei_low_stream" is not used,and Y?

What does the adj actually mean？Is that what I understand？
![image](https://user-images.githubusercontent.com/13513093/172023998-1c10c189-3c44-4d42-b720-c77ec2087227.png)

**Comment by zcaicaros** [comment]
Hi beckhz,

Thank you for your interest in this work.

You are right, `conj_nei_low_stream` is not in use. It stands for the succeeding neighbors of nodes. Since we only consider message flow from source nodes to target nodes, i.e., by following the directions of arcs in disjunctive graphs, we neglect the messages from succeeding nodes.

The `adj` here means `adjacent matrix`.

Regards,
Cong

**Comment by beckhz** [comment]
Thank you for your kind reply

**Comment by beckhz** [comment]
Hi,
I still have two questions.
Let's start with my understanding.
For the disjunctive graph, each point represents a step in the operation, so we have `total_tasks = num_of_jobs*num_of_mechain`. Mapping to the adjacency matrix, we have `adj.shape = (total_task, total_task)`. Then for the adjacency matrix, the lower diagonal array is used as an example, where each cell represents an arc of rows pointing to columns, which is the established process, `O_i1->O_i2`
Based on the above understanding, my question is.
1. why the diagonal array is 1? `O_i1->O_i1` stands for what?
2. `conj_nei_up_stream ` corresponds to the lower diagonal array, and the information expressed seems to be `O_i2-O_i1`, which is exactly the opposite of what I understand, am I wrong?
Please help me to answer the above two questions, thank you very much!

**Comment by zcaicaros** [comment]
1. Since we consider self as a neighbor as well, so diagonal has 1.
2. Ah, I see. Here I implicitly made an assumption that in my code, my `adj` is pointing from row to column.

**Comment by zcaicaros** [comment]
> Hi, I still have two questions. Let's start with my understanding. For the disjunctive graph, each point represents a step in the operation, so we have `total_tasks = num_of_jobs*num_of_mechain`. Mapping to the adjacency matrix, we have `adj.shape = (total_task, total_task)`. Then for the adjacency matrix, the lower diagonal array is used as an example, where each cell represents an arc of rows pointing to columns, which is the established process, `O_i1->O_i2` Based on the above understanding, my question is.
> 
> 1. why the diagonal array is 1? `O_i1->O_i1` stands for what?
> 2. `conj_nei_up_stream ` corresponds to the lower diagonal array, and the information expressed seems to be `O_i2-O_i1`, which is exactly the opposite of what I understand, am I wrong?
>    Please help me to answer the above two questions, thank you very much!

1. Since we consider self as a neighbor as well, so diagonal has 1.
2. Ah, I see. Here I implicitly made an assumption that in my code, my `adj` is pointing from row to column.

**Comment by beckhz** [comment]
Okay, I get it. thx！
